image: tianon/latex

cache:
    key: apt-cache
    untracked: true
    paths:
        - apt-cache/
        - build/

before_script:
    - lualatex -v

build:
    stage: deploy
    environment: Production
    script:
        - mkdir -p build
        - lualatex --output-dir=build resume_cv.tex
        - cd build
          #- pdftoppm -rx 300 -ry 300 -png resume_cv.pdf resume
    artifacts:
        paths:
            - build/

deploy:
    stage: deploy
    before_script:
        - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
        - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y -qq poppler-utils
    script:
        - cd build
        - pdftoppm -rx 300 -ry 300 -png resume_cv.pdf resume
    artifacts:
        paths:
            - build/

